project:
  type: website
  output-dir: docs

website:
  title: "Tom Gibbens-Matsuyama"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: posts.qmd
        text: Posts
      - href: resources.qmd
        text: Resources
  page-footer:
    background: light # or `dark`
    left: Copyright 2024, Tom Gibbens-Matsuyama
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/tommats00/tommats00.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

   


format:
  html:
    theme: styles.scss
    css: styles.css
    toc: true
    page-layout: full



