---
toc: false
---

## A little bit about me 

I’m from Ventura, California, where I spent much of my childhood dreaming of becoming a professional baseball player. However, I quickly realized just how difficult that would be! Fortunately, I had a deep love for the ocean. When we weren’t rushing around to sports events, my family would pack up the car with the cooler and head to the beach. I feel incredibly fortunate to have grown up so close to the coast.

My passion for the ocean eventually led me to study marine biology at the University of Hawaii at Manoa. It was an amazing experience to live in such a beautiful place, and I made many lifelong friendships along the way. It was also during my time there that I discovered the power of programming languages—a discovery that would change the course of my career.

This newfound interest in programming led me to the newly established MEDS program at the Bren School at UCSB. I’m excited to be part of the 4th cohort of this incredible program. The relationships I’ve built here have already been so rewarding, and I’m thrilled to continue growing and learning alongside such inspiring people.

 
## What am i up to? 

I’m currently in my final quarter of my master’s program, and my schedule is packed with classes, my Capstone project, and my TA position. Over the past fall, winter, and spring quarters, I’ve had the pleasure of TA-ing alongside some brilliant graduate students in the PSTAT department. It’s been a fun and rewarding experience to be on the other side of the learning process, teaching students. This journey has really helped me develop the ability to explain complex concepts in different ways, as I’ve learned that not everyone grasps things the same way. It’s crucial to adapt teaching methods to fit diverse learning styles.

For my Capstone project, I’ve had the privilege of working with an amazing client, advisor, and group mates. The client is the California Water Data Consortium, an organization dedicated to creating a resilient and equitable future by ensuring that open and accessible data inform all water management decisions.

